### ISSUE TITLE
In-app subscriptions enabled

### ISSUE THREAD

**Issue by aguilanegra** [aguilanegra/CTAMobileApp#14]
**As a** Application Owner  
**I need** to ensure subscriptions can be purchased on the device
**So that** they can gain access to the app at the proper level
      
### Details and Assumptions
    * Need to perform due diligence for Google Play store
    * Need to leverage existing account in App Store     
### Acceptance Criteria     
```gherkin 
Given there are subscriptions available
When the User purchases a subscription
Then they can access the App at the appropriate level
```

**Comment by leebeckwith** [comment]
Will not be doing it this way.

**Comment by leebeckwith** [comment]
Not planned
